const selectlist = [
    { 
        value:'1',
        label:'vijay'
    },
    { 
        value:'2',
        label:'shradhdha'
    },
    { 
        value:'3',
        label:'rlabelhi'
    },
    { 
        value:'4',
        label:'vishal'
    },
    { 
        value:'5',
        label:'virin'
    },
    { 
        value:'6',
        label:'vihana'
    },
    { 
        value:'7',
        label:'rinku'
    },
    { 
        value:'8',
        label:'ruchi'
    },
    { 
        value:'9',
        label:'dimple'
    },
    { 
        value:'10',
        label:'apeksha'
    },
    { 
        value:'11',
        label:'bittu'
    },
    { 
        value:'13',
        label:'chirag'
    },
    { 
        value:'14',
        label:'disha'
    },
    { 
        value:'15',
        label:'eric'
    },
    { 
        value:'16',
        label:'foram'
    },
    { 
        value:'17',
        label:'gina'
    },
    { 
        value:'18',
        label:'harsh'
    },
    { 
        value:'19',
        label:'isha'
    },
    { 
        value:'20',
        label:'jhalak'
    },
    { 
        value:'21',
        label:'karan'
    },
    { 
        value:'22',
        label:'laksh'
    },
    { 
        value:'23',
        label:'minal'
    },
    { 
        value:'24',
        label:'nimit'
    },
    { 
        value:'25',
        label:'omkar'
    },
    { 
        value:'26',
        label:'pinal'
    },
    { 
        value:'27',
        label:'quinn'
    },
    { 
        value:'28',
        label:'rakshit'
    },
    { 
        value:'29',
        label:'shree'
    },
    { 
        value:'30',
        label:'tina'
    },
    { 
        value:'31',
        label:'utkarsh'
    },
    { 
        value:'32',
        label:'vishnu'
    },
    { 
        value:'33',
        label:'winnie'
    },
    { 
        value:'34',
        label:'xoe'
    },
    { 
        value:'35',
        label:'yaksh'
    },
    { 
        value:'36',
        label:'zainab'
    },
    
];
const express = require('express');
const app = express.Router();
app.get('/',(req, res)=>{
    res.send(selectlist);
})
module.exports = app;